modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="shinyhorses"
version="1.2"
displayName="Shiny Horses Forge - Enchantable Horse Armor"
credits="Credit goes to tfarecnim for the original mod and Dragonostic for the Fabric version."
displayURL="https://www.curseforge.com/minecraft/mc-mods/shiny-horses-forge-enchantable-horse-armor"
authors="tinytransfem"
logoFile="logo.png"
description='''Enchant horse armor and gallop over the freezing ocean!'''

[[dependencies.shinyhorses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.shinyhorses]]
    modId="simplekelpies"
    mandatory=false
    versionRange="[1.1.2,)"
    ordering="NONE"
    side="BOTH"




